=== Heshamabdo21/TASystemsAPIs/src/test/resources/testDataFiles/Lookups_ports_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "page": {
      "type": "integer"
    },
    "size": {
      "type": "integer"
    },
    "totalPages": {
      "type": "integer"
    },
    "totalElements": {
      "type": "integer"
    },
    "content": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "nameArabic": {
              "type": "string"
            },
            "nameEnglish": {
              "type": "string"
            },
            "cityId": {
              "type": "integer"
            },
            "isActive": {
              "type": "boolean"
            },
            "lastUpdated": {
              "type": "string"
            },
            "sectors": {
              "type": "null"
            }
          },
          "required": [
            "id",
            "nameArabic",
            "nameEnglish",
            "cityId",
            "isActive",
            "lastUpdated",
            "sectors"
          ]
        }
      ]
    }
  },
  "required": [
    "page",
    "size",
    "totalPages",
    "totalElements",
    "content"
  ]
}

=== Heshamabdo21/TASystemsAPIs/allure-results/ca9d8e87-079c-49ba-a1b7-89f2c9165d6a-attachment.json
{
  "size": 1,
  "totalPages": 2,
  "page": 0,
  "content": [
    {
      "periodMaxQuotaPerPeriod": 300.0,
      "endDate": "2022-11-14T16:00:00Z",
      "periodProgramTemplates": [
        313,
        314,
        315
      ],
      "id": 188,
      "startDate": "2022-10-24T00:00:00Z",
      "status": "Active"
    }
  ],
  "totalElements": 2
}
